import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');
const isSmallScreen = screenWidth < 350;

export const adminDashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: isSmallScreen ? 15 : 20,
    paddingTop: 65,
    paddingBottom: 15,
    backgroundColor: '#fff',
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  logoImage: {
    width: isSmallScreen ? 16 : 19,
    height: isSmallScreen ? 16 : 19,
    borderRadius: 5,
  },
  logoText: {
    fontSize: isSmallScreen ? 18 : 20,
    fontWeight: 'bold',
    color: '#333',
    fontFamily: 'helvetica',
    marginLeft: 4,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: isSmallScreen ? 6 : 8,
    paddingVertical: 4,
  },
  logoutText: {
    fontSize: isSmallScreen ? 11 : 12,
    color: '#dc3545',
    marginLeft: 4,
    fontWeight: '500',
  },
  settingsButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#f8f9fa',
  },
  welcomeSection: {
    padding: isSmallScreen ? 15 : 20,
    backgroundColor: '#fff',
  },
  welcomeTitle: {
    fontSize: isSmallScreen ? 18 : 20,
    fontWeight: 'bold',
    color: '#333',
  },

  statsSection: {
    paddingHorizontal: isSmallScreen ? 15 : 20,
    paddingVertical: isSmallScreen ? 15 : 20,
    backgroundColor: '#fff',
    marginBottom: 10,
  },
  statsSectionTitle: {
    fontSize: isSmallScreen ? 16 : 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: isSmallScreen ? 12 : 16,
  },
  statsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: isSmallScreen ? 4 : 8,
  },
  statCard: {
    minWidth: isSmallScreen ? '48%' : '22%',
    maxWidth: '48%',
    flex: 1,
    padding: isSmallScreen ? 8 : 10,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  statNumber: {
    fontSize: isSmallScreen ? 16 : 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: isSmallScreen ? 8 : 9,
    color: '#666',
    fontWeight: '500',
    textAlign: 'center',
    lineHeight: isSmallScreen ? 10 : 12,
    numberOfLines: 2,
  },
  
  // Map Section Styles
  mapSection: {
    paddingHorizontal: isSmallScreen ? 15 : 20,
    paddingVertical: isSmallScreen ? 15 : 20,
    backgroundColor: '#fff',
    marginBottom: 10,
  },
  mapSectionTitle: {
    fontSize: isSmallScreen ? 16 : 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: isSmallScreen ? 12 : 16,
  },
  mapCard: {
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: isSmallScreen ? 10 : 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  mapContainer: {
    marginRight: isSmallScreen ? 8 : 12,
    flexShrink: 0,
  },
  mapPlaceholder: {
    width: isSmallScreen ? 60 : 70,
    height: isSmallScreen ? 60 : 70,
    backgroundColor: '#E3F2FD',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#1976D2',
    borderStyle: 'dashed',
    paddingVertical: 6,
  },
  mapPreview: {
    width: 80,
    height: 80,
    borderRadius: 12,
  },
  mapOverlay: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  mapOverlayText: {
    fontSize: 8,
    color: 'white',
    fontWeight: '500',
  },
  mapPlaceholderText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#1976D2',
    marginTop: 6,
    textAlign: 'center',
  },
  mapInfo: {
    flex: 1,
    minWidth: 0,
  },
  mapTitle: {
    fontSize: isSmallScreen ? 13 : 14,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  mapDescription: {
    fontSize: isSmallScreen ? 10 : 11,
    color: '#666',
    marginBottom: 10,
    lineHeight: isSmallScreen ? 13 : 14,
  },
  mapStats: {
    flexDirection: isSmallScreen ? 'column' : 'row',
    flexWrap: 'wrap',
    gap: isSmallScreen ? 4 : 8,
  },
  mapStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    minWidth: 0,
    flexShrink: 1,
  },
  mapStatText: {
    fontSize: isSmallScreen ? 9 : 10,
    color: '#666',
    fontWeight: '500',
    flexShrink: 1,
  },
  menuSection: {
    paddingHorizontal: isSmallScreen ? 15 : 20,
    paddingVertical: isSmallScreen ? 15 : 20,
  },
  menuSectionTitle: {
    fontSize: isSmallScreen ? 16 : 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: isSmallScreen ? 12 : 16,
  },
  menuGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: isSmallScreen ? 4 : 8,
  },
  menuCard: {
    width: isSmallScreen ? '31%' : '30%',
    minWidth: isSmallScreen ? 80 : 90,
    alignItems: 'center',
    marginBottom: isSmallScreen ? 12 : 16,
  },
  menuIconContainer: {
    width: isSmallScreen ? 50 : 55,
    height: isSmallScreen ? 50 : 55,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  menuLabel: {
    fontSize: isSmallScreen ? 10 : 11,
    color: '#333',
    textAlign: 'center',
    fontWeight: '600',
    marginTop: 2,
    lineHeight: isSmallScreen ? 12 : 14,
  },
  
  infoSection: {
    paddingHorizontal: isSmallScreen ? 15 : 20,
    paddingBottom: isSmallScreen ? 15 : 20,
  },
  infoTitle: {
    fontSize: isSmallScreen ? 16 : 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  infoSubtitle: {
    fontSize: isSmallScreen ? 13 : 14,
    color: '#666',
    marginBottom: isSmallScreen ? 15 : 20,
    lineHeight: isSmallScreen ? 18 : 20,
  },
  infoCard: {
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  infoIconContainer: {
    width: 40,
    height: 40,
    backgroundColor: '#E3F2FD',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  infoContent: {
    flex: 1,
  },
  infoCardTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  infoCardSubtitle: {
    fontSize: 12,
    color: '#666',
    lineHeight: 16,
  },
});