import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  contentContainer: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 65,
    marginBottom: 38,
  },
  logoImage: {
    width: 25,
    height: 25,
    borderRadius: 4,
  },
  logoText: {
    fontSize: 28,
    fontWeight: '800',
    color: '#333',
    marginLeft: 5,
    letterSpacing: 1,
  },
  logoSubText: {
    fontSize: 16,
    color: '#666',
    fontWeight: '500',
  },
  illustrationContainer: {
    width: width * 0.7,
    height: 140,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
  },
  warehouseContainer: {
    position: 'relative',
  },
  warehouse: {
    position: 'relative',
  },
  warehouseRoof: {
    width: 140,
    height: 30,
    backgroundColor: '#8D6E63',
    position: 'relative',
    alignItems: 'center',
  },
  roofTop: {
    width: 0,
    height: 0,
    borderLeftWidth: 70,
    borderRightWidth: 70,
    borderBottomWidth: 25,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#6D4C41',
    position: 'absolute',
    top: -25,
  },
  warehouseBody: {
    width: 140,
    height: 90,
    backgroundColor: '#BCAAA4',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  warehouseDoor: {
    position: 'absolute',
    left: 15,
    bottom: 0,
    width: 25,
    height: 50,
    backgroundColor: '#5D4037',
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
  },
  warehouseWindows: {
    position: 'absolute',
    top: 15,
    right: 20,
    flexDirection: 'row',
    gap: 10,
  },
  window: {
    width: 18,
    height: 15,
    backgroundColor: '#E3F2FD',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: '#90A4AE',
  },
  warehouseBoxes: {
    position: 'absolute',
    bottom: -20,
    left: 50,
    flexDirection: 'row',
    gap: 5,
  },
  box: {
    width: 15,
    height: 15,
    backgroundColor: '#FF9800',
    borderRadius: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  textContainer: {
    alignItems: 'center',
    marginBottom: 30,
    paddingHorizontal: 20,
  },
  welcomeText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 10,
  },
  descriptionText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    lineHeight: 20,
  },
  formContainer: {
    width: '100%',
    marginBottom: 30,
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
    marginLeft: 4,
  },
  inputWrapper: {
    position: 'relative',
    backgroundColor: 'white',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#5e5e5e',
    minHeight: 50,
  },
  inputIcon: {
    position: 'absolute',
    left: 15,
    top: '50%',
    transform: [{ translateY: -10 }],
    zIndex: 1,
  },
  input: {
    paddingVertical: 18,
    paddingLeft: 50,
    paddingRight: 15,
    fontSize: 18,
    color: '#5e5e5e',
    borderWidth: 0,
    outlineWidth: 0,
    minHeight: 50,
  },
  inputWrapperFocused: {
    borderColor: '#2196F3',
    borderWidth: 2,
  },
  buttonContainer: {
    width: '100%',
    marginBottom: 30,
  },
  loginButton: {
    backgroundColor: '#1976D2',
    paddingVertical: 15,
    borderRadius: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  disabledButton: {
    opacity: 0.7,
  },
  loginButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  forgotPasswordContainer: {
    alignItems: 'center',
    marginTop: 16,
  },
  forgotPasswordText: {
    color: '#1976D2',
    fontSize: 14,
    fontWeight: '500',
  },
  footer: {
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  versionText: {
    fontSize: 12,
    color: '#999',
  },
});